version: '2'
services:
  app:
    image: gitlab/gitlab-ce:latest
    expose:
      - 80
      - 22
    hostname: ${VIRTUAL_HOST}
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    restart: always
    networks:
      - default
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
