version: '2'
services:
  app:
    image: gitlab/gitlab-ce:latest
    expose:
      - 80
      - 22
    hostname: gitlab.nguyenantoine.com
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    restart: always
    environment:
      - VIRTUAL_HOST=gitlab.nguyenantoine.com
      - LETSENCRYPT_HOST=gitlab.nguyenantoine.com
      - LETSENCRYPT_EMAIL=antoine.ngu@outlook.fr
      - GITLAB_OMNIBUS_CONFIG="external_url 'https://gitlab.nguyenantoine.com'"
    networks:
      - default
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
